apiVersion: v2
kubeVersion: ">= v1.21.0-0"
name: example-backend

version: 0.0.1-dev
appVersion: 1.0.0

description: Example chart for the AWS DevOps Office Hours - example-backend
type: application

keywords:
  - example-backend
  - office-hours
  - devops
home: https://github.com/datariah/example-backend
sources:
  - https://github.com/datariah/example-backend
