repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: fd0556d
  hooks:
  - id: go-fmt
  # - id: go-vet
  - id: go-lint
  - id: go-imports
  - id: go-cyclo
    args: [-over=15]
  - id: no-go-testing
  - id: go-build
  - id: go-mod-tidy
