---
name: 'PR Checks'
on:
  - pull_request
permissions:
  pull-requests: read
jobs:
  golangci:
    name: Golang CI Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16' # Should match our go.mod!
      - run: go test ./...
    needs:
      - golangci
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: buildpacks/github-actions/setup-pack@v4.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16' # Should match our go.mod!
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build backend binary
        run: go build ./...
      - name: Set pack default builder to Paketo
        run: pack config default-builder paketobuildpacks/builder:base
      - name: Build kmai/example-backend docker image with tag "latest"
        run: pack build kmai/example-backend:latest
      - name: Push docker image to Docker Hub
        run: docker push kmai/example-backend:latest
    needs:
      - test
